config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/search' => 'pages#search'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  resources :listings
  resources :listings do
    resources :reservations, only: [:create, :destroy]
  end
  get 'reservations/index'

  resources :listings do
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/ajaxsearch' => 'pages#ajaxsearch'

end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_one :reservation
  has_one :review

  mount_uploader :listing_image, ImageUploader

  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    @listings = Listing.where(complete: false)
  end

  def show
    @reservation = Reservation.find_by(listing_id: params[:id])

    @review = Review.find_by(listing_id: params[:id])
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    if @listing.save
      redirect_to listings_path, notice: 'リスティングを作成しました'
    else
      flash.now[:alert] = 'リスティングの作成に失敗しました'
      render :new
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to listings_path, notice: 'リスティングを編集しました'
    else
      render :edit
    end
  end

  def destroy
    @listing.destroy
    redirect_to listings_path
  end

  private
  def listing_params
    params.require(:listing).permit(:listing_image, :listing_title, :listing_content, :address, :pickup_times)
  end

  def set_listing
    @listing = Listing.find(params[:id])
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/edit.html.erb
<%= render "partial/navbar" %>

<div class="main posts-new">
  <div class="container">
    <div class="contents">
      <h1 class="form-heading">編集する</h1>
      <div class="form">
        <div class="form-body">
          <% @listing.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>

          <%= form_for @listing do |f| %>
            <div class="form-group">
              <%= f.label :画像 %>
              <%= f.file_field :listing_image %>
            </div>
            <div class="form-group">
              <%= f.label :食材・食品名 %>
              <%= f.text_field :listing_title, value: @listing.listing_title, class: 'form-control', required: 'true' %>
            </div>
            <div class="form-group">
              <%= f.label :概要 %>
              <%= f.text_area :listing_content, value: @listing.listing_content, class: 'form-control', required: 'true' %>
            </div>
            <div class="form-group">
              <%= f.label :受け渡し場所 %>
              <%= f.text_field :address, class: 'form-control', required: 'true' %>
            </div>
            <div class="form-group">
              <%= f.label :受け渡し時間 %>
              <%= f.text_field :pickup_times, class: 'form-control', required: 'true' %>
            </div>

            <%= f.submit "保存" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<%= render "partial/navbar" %>

<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="listing-content">
          <div class="row">
            <% @listings.reverse.first(12).each do |listing| %>
              <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="listing-box">
                  <div class="listing-user-data">
                    <div class="listing-user-image listing-user-data-content">
                      <img src="<%= "/user_images/#{listing.user.image}" %>">
                    </div>
                    <div class="listing-user-name listing-user-data-content">
                      <%= link_to(listing.user.name, "/users/#{listing.user.id}") %>
                    </div>
                  </div>
                  <div class="listing-data">
                    <div class="listing-wrap">
                        <%= link_to image_tag(listing.listing_image.url, {:border => '0'}), "/listings/#{listing.id}" %>
                    </div>
                    <div class="listing-title">
                      <%= listing.listing_title %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/new.html.erb
<%= render "partial/navbar" %>

<div class="main posts-new">
  <div class="container">
    <div class="contents">
      <h1 class="form-heading">おすそわけする</h1>
      <div class="form">
        <div class="form-body">
          <% @listing.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>

          <%= form_for @listing do |f| %>
            <div class="form-group">
              <%= f.label :画像 %>
              <%= f.file_field :listing_image %>
            </div>
            <div class="form-group">
              <%= f.label :食材・食品名 %>
              <%= f.text_field :listing_title, class: 'form-control', required: 'true' %>
            </div>
            <div class="form-group">
              <%= f.label :概要 %>
              <%= f.text_area :listing_content, class: 'form-control', required: 'true' %>
            </div>
            <div class="form-group">
              <%= f.label :受け渡し場所 %>
              <%= f.text_field :address, class: 'form-control', required: 'true' %>
            </div>
            <div class="form-group">
              <%= f.label :受け渡し時間 %>
              <%= f.text_field :pickup_times, class: 'form-control', required: 'true' %>
            </div>

            <%= f.submit "作成" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/listings/show.html.erb
<%= render "partial/navbar" %>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item" style="background-image">
      <%= image_tag @listing.listing_image.url%>
    </div>
  </div>
</div>

<!-- Page Content -->
<section class="py-5">
  <div class="container">
    <div class="listing-show-item">
      <!-- ユーザー情報 -->
      <div class="listing-show-user-image">
        <img src="<%= "/user_images/#{@listing.user.image}" %>">
      </div>
      <div class="listing-show-user-name">
        <%= link_to(@listing.user.name, "/users/#{@listing.user.id}") %>
      </div>
    </div>
    <div class="listing-show-text">
      <h1>
        <%= @listing.listing_title %>
      </h1>
      <p>
        <%= @listing.listing_content %>
      </p>
    </div>

    <!-- google map    -->
    <div class="row">
        <div class="col-md-9">
            <h3 class="row-space-3">受け渡し場所</h3>
            <div id="map"></div>
        </div>

        <div class="col-md-3">

        </div>
    </div>
    <style>
        #map{
            width: 100%;
            height: 350px;
        }

    </style>

    <!-- 受け渡し時間 -->
    <div class="row">
      <div class="col-md-9">
        <h3 class="row-space-3">受け渡し時間</h3>
        <p>
          <%= @listing.pickup_times %>
        </p>
      </div>
    </div>

    <div class="listing-button">
      <% if @listing.complete == true %>
        <button type="button" class="btn btn-danger btn-lg" disabled>この取引は終了しています</button>
      <% else %>
        <% if @listing.user_id == current_user.id %>
          <!-- リスティングの編集・削除 -->
          <div class="listing-user-button">
            <%= link_to "編集", "/listings/#{@listing.id}/edit" %>
            <%= link_to "削除", "/listings/#{@listing.id}", {method: "delete"} %>
          </div>
        <% else %>
          <!-- リスティングの予約 -->
          <% if !@reservation.nil? %>
            <% if @reservation.user_id == current_user.id %>
              <%= link_to new_listing_review_path(@listing) do %>
                <button type="button" class="btn btn-danger btn-lg">受け取りました</button>
              <% end %>
              <div class="listing-cancel">
                <%= link_to "キャンセルする", listing_reservation_path(@listing), {method: "delete"} %>
              </div>
            <% else %>
              <button type="button" class="btn btn-danger btn-lg" disabled>予約済みです</button>
            <% end %>
          <% else %>
            <%= link_to listing_reservations_path(@listing), {method: "post"} do %>
              <button type="button" class="btn btn-danger btn-lg">予約する</button>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>

  </div>
</section>

<script>
function initMap() {

  // Create the map.
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 14,
    center: {lat: <%=@listing.latitude %>, lng: <%=@listing.longitude %>},
    mapTypeId: google.maps.MapTypeId.TERRAIN
  });

  // Add the circle for this city to the map.
  var cityCircle = new google.maps.Circle({
    strokeColor: '#FF0000',
    strokeOpacity: 0.8,
    strokeWeight: 2,
    fillColor: '#FF0000',
    fillOpacity: 0.35,
    map: map,
    center: {lat: <%=@listing.latitude %>, lng: <%=@listing.longitude %>},
    radius: 500
  })

}

</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQpt9HosBNr4ToKp5diw2SNymRvH0V8q8&signed_in=true&callback=initMap">
</script>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>