config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/search' => 'pages#search'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  resources :listings
  resources :listings do
    resources :reservations, only: [:create, :destroy]
  end
  get 'reservations/index'

  resources :listings do
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/ajaxsearch' => 'pages#ajaxsearch'

end

app/views/partial/_deviseErrorMsg.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>');
    <% end %>
  </script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-devise">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
          <%= link_to "Osusowake", listings_path, class: "navbar-brand" %>

          <!-- Location Search Form -->
          <div class="navbar-form navbar-left form-group row-space-2">
            <%= form_tag search_path, method: :get do %>
              <%= text_field_tag :search, params[:search], placeholder: "場所の検索", class: "form-control",id:"pac-input" %>
            <% end %>
          </div>

        <% else %>
          <%= link_to "Osusowake", root_path, class: "navbar-brand" %>
        <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <!-- ログインをしている時 -->
          <li><%= link_to "おすそわけする", new_listing_path %></li>
          <li>
            <%= link_to conversations_path do %>
              <i class="fa fa-envelope"></i> メッセージ
            <% end %>
          </li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if current_user.provider %>
              <!-- 認証ログインをしている時 -->
              <%= image_tag current_user.image, class:"image-circle profile-0" %>
            <% end %>
            <%= current_user.name.split("@")[0] %>
            <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", user_path(current_user)%></li>
            <li><%= link_to "予約一覧", reservations_index_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, {method:  :delete} %></li>
          </ul>
        </li>
        <% else %>
          <!-- ログインをしていない時 -->
          <li><%= link_to "アカウント作成", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script>
function initMap() {
  var input = /** @type {!HTMLInputElement} */(
  document.getElementById('pac-input'));

  var autocomplete = new google.maps.places.Autocomplete(input);

  autocomplete.addListener('place_changed', function() {

    var place = autocomplete.getPlace();
    var lat = place.geometry.location.lat();
    var lng = place.geometry.location.lng();

    document.getElementById('lat').value = lat ;
    document.getElementById('lng').value = lng ;

    if (!place.geometry) {
      window.alert("Autocomplete's returned place contains no geometry");
      return;
    }

  });
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAQpt9HosBNr4ToKp5diw2SNymRvH0V8q8&signed_in=true&libraries=places&callback=initMap"
    async defer></script>