config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/search' => 'pages#search'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }

  resources :users, only: [:show]
  resources :listings
  resources :listings do
    resources :reservations, only: [:create, :destroy]
  end
  get 'reservations/index'

  resources :listings do
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/ajaxsearch' => 'pages#ajaxsearch'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @listing = Listing.find(params[:listing_id])
  end

  def create
    @review = Review.create(review_params)
    @listing = Listing.find(@review.listing_id)
    @review.user_id = @listing.user_id
    @review.save

    @reservation = Reservation.find_by(listing_id: @listing.id)
    @reservation.destroy

    @listing.complete = true
    @listing.save

    redirect_to listings_path
  end

  def destroy
  end

  private
  def review_params
    params.require(:review).permit(:description, :rate, :listing_id)
  end
end

app/views/reviews/new.html.erb
<%= render "partial/navbar" %>

<div class="main posts-new">
  <div class="container">
    <div class="contents">
      <h1 class="form-heading">評価する</h1>
      <div class="form">
        <div class="form-body">
          <% @review.errors.full_messages.each do |message| %>
            <div class="form-error">
              <%= message %>
            </div>
          <% end %>

          <%= form_for(@review, url: listing_reviews_path(@listing), html: {method: "post"}) do |f| %>

            <div id="rate_stars"></div>

            <div class="form-group">
              <%= f.text_area :description, class: 'form-control', required: 'true' %>
            </div>

            <%= f.hidden_field :listing_id, value: @listing.id %>

            <%= f.submit "送信" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#rate_stars").raty({
    path: '/assets',
    scoreName: 'review[rate]',
    score: 1
  });
</script>